# Generated by Django 5.2.8 on 2025-11-28 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente_id', models.CharField(max_length=20, unique=True, verbose_name='ID Expediente')),
                ('asunto', models.TextField(verbose_name='Asunto Detallado')),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('atendido', 'Atendido / Finalizado'), ('observado', 'Observado'), ('archivado', 'Archivado / Cancelado')], default='en_proceso', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite_total', models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento del Trámite')),
                ('fecha_limite_paso_actual', models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento del Paso Actual')),
                ('paso_actual', models.IntegerField(default=1, verbose_name='Número de paso actual')),
                ('remitente', models.CharField(max_length=200)),
                ('tipo_remitente', models.CharField(choices=[('PN', 'Persona Natural'), ('PJ', 'Persona Jurídica (Empresa)')], default='PN', max_length=2)),
                ('identificador_remitente', models.CharField(blank=True, max_length=11, null=True, verbose_name='DNI/RUC')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
            options={
                'verbose_name': 'Expediente',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('plazo_dias_habiles', models.PositiveIntegerField(help_text='Plazo total máximo en días hábiles')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_organizativa', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('enlace', models.CharField(blank=True, max_length=255, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion.perfilusuario')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('paso_flujo', models.IntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo_respuesta', models.FileField(blank=True, null=True, upload_to='respuestas/')),
                ('tipo', models.CharField(choices=[('inicio', 'Inicio de Trámite'), ('derivacion', 'Derivación Automática'), ('observacion', 'Observación / Retorno'), ('finalizacion', 'Finalización')], default='derivacion', max_length=20)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.documento')),
                ('unidad_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='gestion.perfilusuario')),
                ('usuario_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='gestion.perfilusuario')),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='responsable_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_asignados', to='gestion.perfilusuario'),
        ),
        migrations.AddField(
            model_name='documento',
            name='procedimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.procedimiento', verbose_name='Trámite TUPA/MPI'),
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='gestion.procedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='PasoFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('plazo_dias', models.PositiveIntegerField(default=1, help_text='Días para completar este paso específico')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='gestion.procedimiento')),
                ('rol_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.rol')),
            ],
            options={
                'ordering': ['procedimiento', 'orden'],
                'unique_together': {('procedimiento', 'orden')},
            },
        ),
    ]
