# Generated by Django 5.2.8 on 2025-11-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='respuestas/', verbose_name='Adjunto del Paso'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('observado', 'Observado / Devuelto'), ('externo', 'En Trámite Externo (MINEDU/SUNEDU)'), ('atendido', 'Atendido / Finalizado'), ('archivado', 'Archivado / Cancelado')], default='en_proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('inicio', 'Inicio de Trámite'), ('derivacion', 'Derivación Automática'), ('observacion', 'Observación / Retorno'), ('externo', 'Envío Externo'), ('finalizacion', 'Finalización')], default='derivacion', max_length=20),
        ),
    ]
