# Generated by Django 5.2.8 on 2025-11-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_movimiento_archivo_adjunto_alter_documento_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='archivo_respuesta',
        ),
    ]
