# Generated by Django 5.2.8 on 2025-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_movimiento_archivo_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('inicio', 'Inicio de Trámite'), ('derivacion', 'Derivación Automática'), ('observacion', 'Observación / Retorno'), ('externo', 'Envío Externo'), ('redireccion', 'Redirección por Error'), ('anulacion', 'Anulación / Cancelación'), ('finalizacion', 'Finalización')], default='derivacion', max_length=20),
        ),
    ]
