# Generated by Django 5.2.8 on 2025-12-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha del Feriado')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Motivo (ej. Navidad)')),
            ],
            options={
                'verbose_name': 'Día Feriado',
                'verbose_name_plural': 'Días Feriados / No Laborables',
                'ordering': ['-fecha'],
            },
        ),
    ]
