# Generated by Django 5.2.8 on 2025-12-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_diaferiado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2025)),
                ('tipo', models.CharField(default='RESOLUCION_DIRECTORAL', max_length=50)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('anio', 'tipo')},
            },
        ),
    ]
