# Generated by Django 5.2.8 on 2025-12-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_correlativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEdicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambios', models.TextField(help_text='Descripción detallada de lo que cambió (JSON o Texto)')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_edicion', to='gestion.documento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.perfilusuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
