# Generated by Django 5.2.8 on 2025-12-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_logedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='roles_inician',
            field=models.ManyToManyField(blank=True, related_name='procedimientos_iniciables', to='gestion.rol'),
        ),
    ]
