# Generated by Django 5.2.8 on 2025-12-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_procedimiento_roles_inician'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='es_jefe',
            field=models.BooleanField(default=False, verbose_name='Es Jefe de Área'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('inicio', 'Inicio de Trámite'), ('derivacion', 'Derivación Automática'), ('asignacion_interna', 'Asignación Interna'), ('observacion', 'Observación / Retorno'), ('externo', 'Envío Externo'), ('redireccion', 'Redirección por Error'), ('anulacion', 'Anulación / Cancelación'), ('finalizacion', 'Finalización')], default='derivacion', max_length=20),
        ),
    ]
