# Generated by Django 5.2.8 on 2025-12-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_rol_es_jefe_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='clave_seguridad',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Clave Web'),
        ),
    ]
