# Generated by Django 5.2.8 on 2025-12-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_documento_clave_seguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Celular de Contacto'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
    ]
